### ISSUE TITLE
Flags enums are not serialized when multiple flags are set

### ISSUE THREAD

**Issue by jhranac** [ExtendedXmlSerializer/home#386]
Hi, 

I've encountered an issue with Flags enums. When multiple flags are set the enum value is serialized as null. Works fine with only one flag. 

Code to repro: 
```c#
        [Test]
        public void FlagsEnumSerializationWorks()
        {
            var config = new ConfigurationContainer();
            var serializer = config.Create();
            
            var input = new FlagsEnumContainer(LogMessageSeverity.Debug | LogMessageSeverity.Informational);
            var clone = Clone(input, serializer);

            Assert.AreEqual(input.Value, clone.Value);
        }

        public class FlagsEnumContainer
        {
            public LogMessageSeverity Value { get; set; }

            public FlagsEnumContainer()
            {
            }

            public FlagsEnumContainer(LogMessageSeverity value)
            {
                Value = value;
            }
        }

        public enum LogMessageSeverity
        {
            Debug = 0b1, 
            Informational = 0b10, 
            Critical = 0b100
        }

        public T Clone<T>(T objectToClone, IExtendedXmlSerializer serializer)
        {
            using var stream = new MemoryStream();
            serializer.Serialize(stream, objectToClone);
            stream.Seek(0, SeekOrigin.Begin);
            return serializer.Deserialize<T>(stream);
        }
```

Given the above example, the code:
```c#
var input = new FlagsEnumContainer(LogMessageSeverity.Debug | LogMessageSeverity.Informational);
string serialized = serializer.Serialize(new XmlWriterSettings {Indent = true}, input);
```
produces incorrectly
```xml
<?xml version="1.0" encoding="utf-8"?>
<SerializationTests-FlagsEnumContainer xmlns="clr-namespace:AutoSliceAndView.Core.Tests;assembly=AutoSliceAndView.Core.Tests">
  <Value xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
</SerializationTests-FlagsEnumContainer>
```

while this snippet works
```c#
var input = new FlagsEnumContainer(LogMessageSeverity.Debug);
string serialized = serializer.Serialize(new XmlWriterSettings {Indent = true}, input);
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<SerializationTests-FlagsEnumContainer xmlns="clr-namespace:AutoSliceAndView.Core.Tests;assembly=AutoSliceAndView.Core.Tests">
  <Value>Debug</Value>
</SerializationTests-FlagsEnumContainer>
```

**Comment by Mike-E-wins** [comment]
Ah!  Indeed, @jhranac ... nice find.  I've committed a fix that (hopefully 😁) addresses this issue.

Here are the instructions to try it out:

https://github.com/ExtendedXmlSerializer/home/pull/387#issuecomment-616658240

Please let me know of any issues that you find and/or questions you might have and I'll do my best to help you out. 👍

**Comment by jhranac** [comment]
With the new version I'm getting another type of an issue: 
```
System.InvalidCastException : Specified cast is not valid.
   at ExtendedXmlSerializer.ContentModel.Conversion.EnumerationConverters.Converters.Converter.Format(Enum instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Conversion\EnumerationConverters.cs:line 37
   at ExtendedXmlSerializer.ContentModel.Content.ContentWriter.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\ContentWriter.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Content.Enclosure`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\Enclosure.cs:line 29
   at ExtendedXmlSerializer.ContentModel.Members.MemberWriter.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberWriter.cs:line 26
   at ExtendedXmlSerializer.ContentModel.Members.MemberListWriter.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberListWriter.cs:line 18
   at ExtendedXmlSerializer.ContentModel.Content.Enclosure`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\Enclosure.cs:line 29
   at ExtendedXmlSerializer.ExtensionModel.Xml.Write.Execute(Writing parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Write.cs:line 21
   at ExtendedXmlSerializer.ExtensionModel.Xml.Serializer.Serialize(XmlWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Serializer.cs:line 19
   at ExtendedXmlSerializer.ExtensionModel.Xml.InstanceFormatter.Get(Object parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\InstanceFormatter.cs:line 33
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Serialize(IExtendedXmlSerializer this, Stream stream, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionMethodsForSerialization.cs:line 54
```
I've just found out that the enum we're using does not have int as a base type (it's referenced from a different library). It uses uint which can't be typecasted to int without loss of data.

I'd suggest utilizing 
```c#
Enum.GetUnderlyingType(typeof(LogMessageSeverity))
```
to get specific enum value-type. The only type you have to check should be the ulong/UInt64. Everthing else can be converted to Int64 without any loss of data - but it can't be done using typecasting. Instead use the .net Convert class.

**Comment by Mike-E-wins** [comment]
Weird @jhranac it would seem there's something wrong with the versioning here.  The callstack points to a converter class that was in the first release but removed in the 2nd release yesterday.

I have created a new release with a passing test on an `uint` enumeration type.  You can find that here:
https://github.com/ExtendedXmlSerializer/home/pull/387#issuecomment-617018114

Let's see if that treats you better. ✌

**Comment by jhranac** [comment]
Yup, this works! Thanks for the quick fix.

**Comment by Mike-E-wins** [comment]
Sweet!  I'll merge this in and see if we can get this posted to NuGet in the next week or so, depending on if other issues are reported.  In the meantime feel free to use the preview build. I will update once posted. 👍

**Comment by Mike-E-wins** [comment]
Welp, tried to post but have run into yet another GitHub Actions issue:

https://github.community/t5/GitHub-Actions/Yet-Another-Broken-Build/m-p/56016#M9717

"Brittle" is my impression of this tech.  Should have simply stuck with AppVeyor.  Waiting to hear back to resume.  Please stick with the preview build for now.

**Comment by Mike-E-wins** [comment]
Alrighty!  We are live.  Thank you for contributing and improving the quality of ExtendedXmlSerializer!

https://www.nuget.org/packages/ExtendedXmlSerializer/
